# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Screen(object):
    def __init__(self):
        self.label = None
        self.man = None
        self.whole = None
        self.send = None
        self.character = None
        self.input = None
        self.known = None
        self.enter = None
        self.word = None
        self.horizontalLayoutWidget = None
        self.difficult = None
        self.medium = None
        self.easy = None
        self.horizontalLayout = None
        self.used = None
        self.status = None
        self.tries = None
        self.centralwidget = None

    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(948, 791)
        Window.setStyleSheet("#centralwidget {image: url(:/Images/Images/Background.png);}")
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.status = QtWidgets.QGroupBox(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(70, 290, 261, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.status.setFont(font)
        self.status.setStyleSheet("QGroupBox {border: 1px solid rgb(0, 221, 241); border-radius: 10px; "
                                  "margin-top: 10px; color: white;} QGroupBox::title {subcontrol-origin: "
                                  "margin; left: 7px; padding: 0px 5px 0px 5px;}")
        self.status.setFlat(False)
        self.status.setObjectName("status")
        self.tries = QtWidgets.QLabel(self.status)
        self.tries.setGeometry(QtCore.QRect(0, 30, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tries.setFont(font)
        self.tries.setStyleSheet("color: white;")
        self.tries.setAlignment(QtCore.Qt.AlignCenter)
        self.tries.setObjectName("tries")
        self.used = QtWidgets.QLabel(self.status)
        self.used.setGeometry(QtCore.QRect(0, 80, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.used.setFont(font)
        self.used.setStyleSheet("color: white;")
        self.used.setAlignment(QtCore.Qt.AlignCenter)
        self.used.setObjectName("used")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.status)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 120, 223, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.easy = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.easy.setFont(font)
        self.easy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.easy.setStyleSheet("color: rgb(255, 255, 255);")
        self.easy.setChecked(True)
        self.easy.setObjectName("easy")
        self.horizontalLayout.addWidget(self.easy)
        self.medium = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.medium.setFont(font)
        self.medium.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.medium.setStyleSheet("color: rgb(255, 255, 255);")
        self.medium.setObjectName("medium")
        self.horizontalLayout.addWidget(self.medium)
        self.difficult = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.difficult.setFont(font)
        self.difficult.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.difficult.setStyleSheet("color: rgb(255, 255, 255);")
        self.difficult.setObjectName("difficult")
        self.horizontalLayout.addWidget(self.difficult)
        self.word = QtWidgets.QGroupBox(self.centralwidget)
        self.word.setGeometry(QtCore.QRect(70, 470, 261, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.word.setFont(font)
        self.word.setStyleSheet("QGroupBox {border: 1px solid rgb(0, 221, 241); border-radius: 10px; "
                                "margin-top: 10px; color: white;} QGroupBox::title {subcontrol-origin: "
                                "margin; left: 7px; padding: 0px 5px 0px 5px;}")
        self.word.setFlat(False)
        self.word.setObjectName("word")
        self.known = QtWidgets.QLabel(self.word)
        self.known.setGeometry(QtCore.QRect(0, 30, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.known.setFont(font)
        self.known.setStyleSheet("color: white;")
        self.known.setAlignment(QtCore.Qt.AlignCenter)
        self.known.setObjectName("known")
        self.enter = QtWidgets.QGroupBox(self.centralwidget)
        self.enter.setGeometry(QtCore.QRect(70, 580, 261, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enter.setFont(font)
        self.enter.setStyleSheet("QGroupBox {border: 1px solid rgb(0, 221, 241); border-radius: 10px; "
                                 "margin-top: 10px; color: white;} QGroupBox::title {subcontrol-origin: "
                                 "margin; left: 7px; padding: 0px 5px 0px 5px;}")
        self.enter.setFlat(False)
        self.enter.setObjectName("enter")
        self.input = QtWidgets.QLineEdit(self.enter)
        self.input.setGeometry(QtCore.QRect(20, 50, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.input.setFont(font)
        self.input.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.input.setStyleSheet("border: 1px solid rgb(200, 200, 200); border-radius: 10px;")
        self.input.setText("")
        self.input.setAlignment(QtCore.Qt.AlignCenter)
        self.input.setObjectName("input")
        self.whole = QtWidgets.QRadioButton(self.enter)
        self.whole.setGeometry(QtCore.QRect(220, 20, 16, 20))
        self.whole.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.whole.setText("")
        self.whole.setObjectName("whole")
        self.character = QtWidgets.QRadioButton(self.enter)
        self.character.setGeometry(QtCore.QRect(180, 20, 16, 20))
        self.character.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.character.setText("")
        self.character.setChecked(True)
        self.character.setObjectName("character")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(670, 630, 181, 51))
        self.send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send.setStyleSheet("QPushButton {background-color: rgb(0, 4, 47); color: white; "
                                "border: 3px ridge rgb(0, 10, 60);} "
                                "QPushButton:hover {background-color: rgb(0, 10, 60); border-width: 6px;}")
        self.send.setObjectName("send")
        self.man = QtWidgets.QLabel(self.centralwidget)
        self.man.setGeometry(QtCore.QRect(0, 0, 951, 791))
        self.man.setStyleSheet("")
        self.man.setText("")
        self.man.setObjectName("man")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 951, 791))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 170); color: white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.man.raise_()
        self.status.raise_()
        self.word.raise_()
        self.enter.raise_()
        self.send.raise_()
        self.label.raise_()
        Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Hangman"))
        self.status.setTitle(_translate("Window", "Status"))
        self.tries.setText(_translate("Window", "Tires Left: 5"))
        self.used.setText(_translate("Window", "Used Letters: "))
        self.easy.setText(_translate("Window", "EASY"))
        self.medium.setText(_translate("Window", "MEDIUM"))
        self.difficult.setText(_translate("Window", "HARD"))
        self.word.setTitle(_translate("Window", "The Word"))
        self.known.setText(_translate("Window", "The Word: _ _"))
        self.enter.setTitle(_translate("Window", "Enter"))
        self.input.setPlaceholderText(_translate("Window", "Text Letter"))
        self.send.setText(_translate("Window", "Send"))
        self.label.setText(_translate("Window", "Words.csv File Not Found :("))
